# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr

- name: Install package management prerequisites
  become: true
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - apt-transport-https
      - gpg
      - gpg-agent
      - dirmngr
      - lsb-release
      - curl

- name: Install cmake
  when: lfc_install_cmake
  ansible.builtin.include_tasks: pkg-cmake.yml

- name: Import tasks pkg-rti.yml
  when: lfc_install_rti
  ansible.builtin.include_tasks: pkg-rti.yml

- name: Import java install tasks
  ansible.builtin.import_tasks: pkg-openjre-java.yml

- name: Import tasks pkg-lfc.yml
  ansible.builtin.import_tasks: pkg-lfc.yml
