---
- name: Install libssl-dev
  ansible.builtin.apt:
    pkg: libssl-dev
    state: latest
  become: true

- name: Create cache folder /var/cache/lf-lang
  ansible.builtin.file:
    path: /var/cache/lf-lang
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
  become: true

- name: Git clone lf-lang/reactor-c
  ansible.builtin.git:
    repo: "https://github.com/lf-lang/reactor-c"
    dest: /var/cache/lf-lang/reactor-c
    single_branch: true
    version: main
    depth: 1

- name: Create build folder
  ansible.builtin.file:
    path: /var/cache/lf-lang/build/RTI
    recurse: true
    state: directory

- name: Run cmake
  ansible.builtin.command:
    cmd: cmake -DAUTH=ON /var/cache/lf-lang/reactor-c/core/federated/RTI
    creates: /var/cache/lf-lang/build/RTI/Makefile
  args:
    chdir: /var/cache/lf-lang/build/RTI

- name: Stat build/RTI
  ansible.builtin.stat:
    path: /var/cache/lf-lang/build/RTI/RTI
  register: rti_make_stat

- name: Run make
  community.general.make:
    chdir: /var/cache/lf-lang/build/RTI
  when: not rti_make_stat.stat.exists

- name: Stat /usr/local/bin/RTI
  ansible.builtin.stat:
    path: /usr/local/bin/RTI
  register: rti_system_stat

- name: Run make install
  community.general.make:
    chdir: /var/cache/lf-lang/build/RTI
    target: install
  when: not rti_system_stat.stat.exists
  become: true

- name: Verify RTI installation
  ansible.builtin.command:
    cmd: which RTI
  changed_when: false
  register: rti_installed
  failed_when: rti_installed.rc != 0
