# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Download lingua franca install script
  ansible.builtin.get_url:
    url: https://install.lf-lang.org
    dest: "{{ ansible_env.HOME }}/.cache/install-lf-lang.sh"
    mode: ug+x

- name: Install lingua franca
  ansible.builtin.command:
    cmd: bash {{ ansible_env.HOME }}/.cache/install-lf-lang.sh cli
    creates: "{{ ansible_env.HOME }}/.local/bin/lfc"
  register: lfc_install
  failed_when: lfc_install.rc != 0

- name: Add .local/bin to path
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export PATH=$PATH:{{ ansible_env.HOME }}/.local/bin"
