---
- name: Install libssl-dev
  ansible.builtin.apt:
    pkg: libssl-dev
  become: true

- name: Create cache folder {{ ansible_env.HOME}}/.cache/lf-lang
  ansible.builtin.file:
    path: "{{ ansible_env.HOME}}/.cache/lf-lang"
    state: directory

- name: Git clone lf-lang/reactor-c
  ansible.builtin.git:
    repo: "https://github.com/lf-lang/reactor-c"
    dest: "{{ ansible_env.HOME}}/.cache/lf-lang/reactor-c"
    single_branch: true
    version: main
    depth: 1

- name: Create build folder
  ansible.builtin.file:
    path: "{{ ansible_env.HOME}}/.cache/lf-lang/build/RTI"
    recurse: true
    state: directory

- name: Run cmake
  ansible.builtin.command:
    cmd: cmake -DAUTH=ON {{ ansible_env.HOME}}/.cache/lf-lang/reactor-c/core/federated/RTI
    creates: "{{ ansible_env.HOME}}/.cache/lf-lang/build/RTI/Makefile"
  args:
    chdir: "{{ ansible_env.HOME}}/.cache/lf-lang/build/RTI"

- name: Stat build/RTI
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME}}/.cache/lf-lang/build/RTI/RTI"
  register: rti_make_stat

- name: Run make
  community.general.make:
    chdir: "{{ ansible_env.HOME}}/.cache/lf-lang/build/RTI"
  when: not rti_make_stat.stat.exists

- name: Stat /usr/local/bin/RTI
  ansible.builtin.stat:
    path: /usr/local/bin/RTI
  register: rti_system_stat

- name: Run make install
  community.general.make:
    chdir: "{{ ansible_env.HOME}}/.cache/lf-lang/build/RTI"
    target: install
  when: not rti_system_stat.stat.exists
  become: true

- name: Verify RTI installation
  ansible.builtin.command:
    cmd: which RTI
  changed_when: false
  register: rti_installed
  failed_when: rti_installed.rc != 0
