---
- name: Apt install python
  ansible.builtin.apt:
    pkg:
      - libffi-dev
      - python3-dev
      - python3-pip
      - python3-venv
    state: latest
  become: true

- name: Pip update pip
  ansible.builtin.pip:
    name:
      - pip
      - setuptools
    state: latest

- name: Pip install python packages
  ansible.builtin.pip:
    name:
      - virtualenv
      - pylint
    state: latest
