# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Apt install python
  ansible.builtin.apt:
    pkg:
      - libffi-dev
      - python3-dev
      - python3-pip
      - python3-venv
  become: true

- name: Pip install python packages
  ansible.builtin.pip:
    name:
      - virtualenv
      - pylint
