---
- name: Add apt key
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: EA8CACC073C3DB2A
    keyring: /etc/apt/trusted.gpg.d/oracle-java.gpg
  become: true

- name: Run apt-add-repository ppa:linuxuprising/java
  ansible.builtin.apt_repository:
    repo: "deb http://ppa.launchpad.net/linuxuprising/java/ubuntu {{ ansible_facts['distribution_release'] }} main"
  become: true

- name: Run deb set selection to accept oracle java license
  ansible.builtin.debconf:
    name: oracle-java17-installer
    question: shared/accepted-oracle-license-v1-3
    value: "true"
    vtype: select
  become: true

- name: Install oracle-java17-installer
  ansible.builtin.apt:
    pkg:
      - oracle-java17-installer
      - oracle-java17-set-default
  become: true
