# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Install gcc
  ansible.builtin.apt:
    pkg:
      - build-essential
      - gcc
      - cmake
  become: true
